package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA



/**
 * Doctorconsultationpreferences generated by hbm2java
 */
public class Doctorconsultationpreferences  implements java.io.Serializable {


     private Long idDoctorConsultationPreferences;
     private Doctordetails doctordetails;
     private Roomtypelist roomtypelist;
     private Double doctorConsultationPreferencesPrice;

    public Doctorconsultationpreferences() {
    }

    public Doctorconsultationpreferences(Doctordetails doctordetails, Roomtypelist roomtypelist, Double doctorConsultationPreferencesPrice) {
       this.doctordetails = doctordetails;
       this.roomtypelist = roomtypelist;
       this.doctorConsultationPreferencesPrice = doctorConsultationPreferencesPrice;
    }
   
    public Long getIdDoctorConsultationPreferences() {
        return this.idDoctorConsultationPreferences;
    }
    
    public void setIdDoctorConsultationPreferences(Long idDoctorConsultationPreferences) {
        this.idDoctorConsultationPreferences = idDoctorConsultationPreferences;
    }
    public Doctordetails getDoctordetails() {
        return this.doctordetails;
    }
    
    public void setDoctordetails(Doctordetails doctordetails) {
        this.doctordetails = doctordetails;
    }
    public Roomtypelist getRoomtypelist() {
        return this.roomtypelist;
    }
    
    public void setRoomtypelist(Roomtypelist roomtypelist) {
        this.roomtypelist = roomtypelist;
    }
    public Double getDoctorConsultationPreferencesPrice() {
        return this.doctorConsultationPreferencesPrice;
    }
    
    public void setDoctorConsultationPreferencesPrice(Double doctorConsultationPreferencesPrice) {
        this.doctorConsultationPreferencesPrice = doctorConsultationPreferencesPrice;
    }




}


