package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Doctordetails generated by hbm2java
 */
public class Doctordetails  implements java.io.Serializable {


     private String idDoctorDetails;
     private String doctorDetailsFirstName;
     private String doctorDetailsLastName;
     private Integer doctorDetailsAge;
     private String doctorDetailsSex;
     private Long doctorDetailsContactNumber;
     private Date doctorDetailsDateOfJoining;
     private String doctorDetailsDesignation;
     private String doctorDetailsQualification;
     private String doctorDetailsSpecialization;
     private Double doctorDetailsOpconsultationCharges;
     private String doctorDetailsPassword;
     private String doctorDetailsAddress;
     private Integer doctorDetailsMaxVisits;
     private Integer doctorDetailsNoOfDaysValid;
     private Set opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId = new HashSet(0);
     private Set ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId = new HashSet(0);
     private Set outpatientregistrations = new HashSet(0);
     private Set ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId = new HashSet(0);
     private Set doctorconsultationpreferenceses = new HashSet(0);
     private Set ipregistrationdetailses = new HashSet(0);
     private Set opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId = new HashSet(0);

    public Doctordetails() {
    }

	
    public Doctordetails(String idDoctorDetails) {
        this.idDoctorDetails = idDoctorDetails;
    }
    public Doctordetails(String idDoctorDetails, String doctorDetailsFirstName, String doctorDetailsLastName, Integer doctorDetailsAge, String doctorDetailsSex, Long doctorDetailsContactNumber, Date doctorDetailsDateOfJoining, String doctorDetailsDesignation, String doctorDetailsQualification, String doctorDetailsSpecialization, Double doctorDetailsOpconsultationCharges, String doctorDetailsPassword, String doctorDetailsAddress, Integer doctorDetailsMaxVisits, Integer doctorDetailsNoOfDaysValid, Set opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId, Set ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId, Set outpatientregistrations, Set ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId, Set doctorconsultationpreferenceses, Set ipregistrationdetailses, Set opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId) {
       this.idDoctorDetails = idDoctorDetails;
       this.doctorDetailsFirstName = doctorDetailsFirstName;
       this.doctorDetailsLastName = doctorDetailsLastName;
       this.doctorDetailsAge = doctorDetailsAge;
       this.doctorDetailsSex = doctorDetailsSex;
       this.doctorDetailsContactNumber = doctorDetailsContactNumber;
       this.doctorDetailsDateOfJoining = doctorDetailsDateOfJoining;
       this.doctorDetailsDesignation = doctorDetailsDesignation;
       this.doctorDetailsQualification = doctorDetailsQualification;
       this.doctorDetailsSpecialization = doctorDetailsSpecialization;
       this.doctorDetailsOpconsultationCharges = doctorDetailsOpconsultationCharges;
       this.doctorDetailsPassword = doctorDetailsPassword;
       this.doctorDetailsAddress = doctorDetailsAddress;
       this.doctorDetailsMaxVisits = doctorDetailsMaxVisits;
       this.doctorDetailsNoOfDaysValid = doctorDetailsNoOfDaysValid;
       this.opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId = opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId;
       this.ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId = ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId;
       this.outpatientregistrations = outpatientregistrations;
       this.ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId = ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId;
       this.doctorconsultationpreferenceses = doctorconsultationpreferenceses;
       this.ipregistrationdetailses = ipregistrationdetailses;
       this.opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId = opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId;
    }
   
    public String getIdDoctorDetails() {
        return this.idDoctorDetails;
    }
    
    public void setIdDoctorDetails(String idDoctorDetails) {
        this.idDoctorDetails = idDoctorDetails;
    }
    public String getDoctorDetailsFirstName() {
        return this.doctorDetailsFirstName;
    }
    
    public void setDoctorDetailsFirstName(String doctorDetailsFirstName) {
        this.doctorDetailsFirstName = doctorDetailsFirstName;
    }
    public String getDoctorDetailsLastName() {
        return this.doctorDetailsLastName;
    }
    
    public void setDoctorDetailsLastName(String doctorDetailsLastName) {
        this.doctorDetailsLastName = doctorDetailsLastName;
    }
    public Integer getDoctorDetailsAge() {
        return this.doctorDetailsAge;
    }
    
    public void setDoctorDetailsAge(Integer doctorDetailsAge) {
        this.doctorDetailsAge = doctorDetailsAge;
    }
    public String getDoctorDetailsSex() {
        return this.doctorDetailsSex;
    }
    
    public void setDoctorDetailsSex(String doctorDetailsSex) {
        this.doctorDetailsSex = doctorDetailsSex;
    }
    public Long getDoctorDetailsContactNumber() {
        return this.doctorDetailsContactNumber;
    }
    
    public void setDoctorDetailsContactNumber(Long doctorDetailsContactNumber) {
        this.doctorDetailsContactNumber = doctorDetailsContactNumber;
    }
    public Date getDoctorDetailsDateOfJoining() {
        return this.doctorDetailsDateOfJoining;
    }
    
    public void setDoctorDetailsDateOfJoining(Date doctorDetailsDateOfJoining) {
        this.doctorDetailsDateOfJoining = doctorDetailsDateOfJoining;
    }
    public String getDoctorDetailsDesignation() {
        return this.doctorDetailsDesignation;
    }
    
    public void setDoctorDetailsDesignation(String doctorDetailsDesignation) {
        this.doctorDetailsDesignation = doctorDetailsDesignation;
    }
    public String getDoctorDetailsQualification() {
        return this.doctorDetailsQualification;
    }
    
    public void setDoctorDetailsQualification(String doctorDetailsQualification) {
        this.doctorDetailsQualification = doctorDetailsQualification;
    }
    public String getDoctorDetailsSpecialization() {
        return this.doctorDetailsSpecialization;
    }
    
    public void setDoctorDetailsSpecialization(String doctorDetailsSpecialization) {
        this.doctorDetailsSpecialization = doctorDetailsSpecialization;
    }
    public Double getDoctorDetailsOpconsultationCharges() {
        return this.doctorDetailsOpconsultationCharges;
    }
    
    public void setDoctorDetailsOpconsultationCharges(Double doctorDetailsOpconsultationCharges) {
        this.doctorDetailsOpconsultationCharges = doctorDetailsOpconsultationCharges;
    }
    public String getDoctorDetailsPassword() {
        return this.doctorDetailsPassword;
    }
    
    public void setDoctorDetailsPassword(String doctorDetailsPassword) {
        this.doctorDetailsPassword = doctorDetailsPassword;
    }
    public String getDoctorDetailsAddress() {
        return this.doctorDetailsAddress;
    }
    
    public void setDoctorDetailsAddress(String doctorDetailsAddress) {
        this.doctorDetailsAddress = doctorDetailsAddress;
    }
    public Integer getDoctorDetailsMaxVisits() {
        return this.doctorDetailsMaxVisits;
    }
    
    public void setDoctorDetailsMaxVisits(Integer doctorDetailsMaxVisits) {
        this.doctorDetailsMaxVisits = doctorDetailsMaxVisits;
    }
    public Integer getDoctorDetailsNoOfDaysValid() {
        return this.doctorDetailsNoOfDaysValid;
    }
    
    public void setDoctorDetailsNoOfDaysValid(Integer doctorDetailsNoOfDaysValid) {
        this.doctorDetailsNoOfDaysValid = doctorDetailsNoOfDaysValid;
    }
    public Set getOpconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId() {
        return this.opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId;
    }
    
    public void setOpconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId(Set opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId) {
        this.opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId = opconsultanttransfordetailsesForOpconsultantTransforDetailsPrevConsultantId;
    }
    public Set getIpconstranfordetailsesForIpconsTranforDetailsPrevConsultantId() {
        return this.ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId;
    }
    
    public void setIpconstranfordetailsesForIpconsTranforDetailsPrevConsultantId(Set ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId) {
        this.ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId = ipconstranfordetailsesForIpconsTranforDetailsPrevConsultantId;
    }
    public Set getOutpatientregistrations() {
        return this.outpatientregistrations;
    }
    
    public void setOutpatientregistrations(Set outpatientregistrations) {
        this.outpatientregistrations = outpatientregistrations;
    }
    public Set getIpconstranfordetailsesForIpconsTranforDetailsNewConsultantId() {
        return this.ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId;
    }
    
    public void setIpconstranfordetailsesForIpconsTranforDetailsNewConsultantId(Set ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId) {
        this.ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId = ipconstranfordetailsesForIpconsTranforDetailsNewConsultantId;
    }
    public Set getDoctorconsultationpreferenceses() {
        return this.doctorconsultationpreferenceses;
    }
    
    public void setDoctorconsultationpreferenceses(Set doctorconsultationpreferenceses) {
        this.doctorconsultationpreferenceses = doctorconsultationpreferenceses;
    }
    public Set getIpregistrationdetailses() {
        return this.ipregistrationdetailses;
    }
    
    public void setIpregistrationdetailses(Set ipregistrationdetailses) {
        this.ipregistrationdetailses = ipregistrationdetailses;
    }
    public Set getOpconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId() {
        return this.opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId;
    }
    
    public void setOpconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId(Set opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId) {
        this.opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId = opconsultanttransfordetailsesForOpconsultantTransforDetailsNewConultantId;
    }




}


