package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ipregistrationdetails generated by hbm2java
 */
public class Ipregistrationdetails  implements java.io.Serializable {


     private String idIpregistrationDetails;
     private Patientregistration patientregistration;
     private Doctordetails doctordetails;
     private Userdetails userdetails;
     private Date ipregistrationDetailsRegistrationDateAndTime;
     private String ipregistrationDetailsStatusOfIp;
     private Set ipconstranfordetailses = new HashSet(0);
     private Set iproomtrackdetailses = new HashSet(0);

    public Ipregistrationdetails() {
    }

	
    public Ipregistrationdetails(String idIpregistrationDetails) {
        this.idIpregistrationDetails = idIpregistrationDetails;
    }
    public Ipregistrationdetails(String idIpregistrationDetails, Patientregistration patientregistration, Doctordetails doctordetails, Userdetails userdetails, Date ipregistrationDetailsRegistrationDateAndTime, String ipregistrationDetailsStatusOfIp, Set ipconstranfordetailses, Set iproomtrackdetailses) {
       this.idIpregistrationDetails = idIpregistrationDetails;
       this.patientregistration = patientregistration;
       this.doctordetails = doctordetails;
       this.userdetails = userdetails;
       this.ipregistrationDetailsRegistrationDateAndTime = ipregistrationDetailsRegistrationDateAndTime;
       this.ipregistrationDetailsStatusOfIp = ipregistrationDetailsStatusOfIp;
       this.ipconstranfordetailses = ipconstranfordetailses;
       this.iproomtrackdetailses = iproomtrackdetailses;
    }
   
    public String getIdIpregistrationDetails() {
        return this.idIpregistrationDetails;
    }
    
    public void setIdIpregistrationDetails(String idIpregistrationDetails) {
        this.idIpregistrationDetails = idIpregistrationDetails;
    }
    public Patientregistration getPatientregistration() {
        return this.patientregistration;
    }
    
    public void setPatientregistration(Patientregistration patientregistration) {
        this.patientregistration = patientregistration;
    }
    public Doctordetails getDoctordetails() {
        return this.doctordetails;
    }
    
    public void setDoctordetails(Doctordetails doctordetails) {
        this.doctordetails = doctordetails;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Date getIpregistrationDetailsRegistrationDateAndTime() {
        return this.ipregistrationDetailsRegistrationDateAndTime;
    }
    
    public void setIpregistrationDetailsRegistrationDateAndTime(Date ipregistrationDetailsRegistrationDateAndTime) {
        this.ipregistrationDetailsRegistrationDateAndTime = ipregistrationDetailsRegistrationDateAndTime;
    }
    public String getIpregistrationDetailsStatusOfIp() {
        return this.ipregistrationDetailsStatusOfIp;
    }
    
    public void setIpregistrationDetailsStatusOfIp(String ipregistrationDetailsStatusOfIp) {
        this.ipregistrationDetailsStatusOfIp = ipregistrationDetailsStatusOfIp;
    }
    public Set getIpconstranfordetailses() {
        return this.ipconstranfordetailses;
    }
    
    public void setIpconstranfordetailses(Set ipconstranfordetailses) {
        this.ipconstranfordetailses = ipconstranfordetailses;
    }
    public Set getIproomtrackdetailses() {
        return this.iproomtrackdetailses;
    }
    
    public void setIproomtrackdetailses(Set iproomtrackdetailses) {
        this.iproomtrackdetailses = iproomtrackdetailses;
    }




}


