package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Iproomtrackdetails generated by hbm2java
 */
public class Iproomtrackdetails  implements java.io.Serializable {


     private Long idIproomTrackDetails;
     private Userdetails userdetailsByIproomTrackDetailsOutUserId;
     private Roomwisebedstatusdetails roomwisebedstatusdetails;
     private Roomtypelist roomtypelist;
     private Ipregistrationdetails ipregistrationdetails;
     private Userdetails userdetailsByIproomTrackDetailsInUserId;
     private String iproomTrackDetailsPatientRegistrationId;
     private Date iproomTrackDetailsInDateAndTime;
     private Date iproomTrackDetailsOutDateAndTime;

    public Iproomtrackdetails() {
    }

    public Iproomtrackdetails(Userdetails userdetailsByIproomTrackDetailsOutUserId, Roomwisebedstatusdetails roomwisebedstatusdetails, Roomtypelist roomtypelist, Ipregistrationdetails ipregistrationdetails, Userdetails userdetailsByIproomTrackDetailsInUserId, String iproomTrackDetailsPatientRegistrationId, Date iproomTrackDetailsInDateAndTime, Date iproomTrackDetailsOutDateAndTime) {
       this.userdetailsByIproomTrackDetailsOutUserId = userdetailsByIproomTrackDetailsOutUserId;
       this.roomwisebedstatusdetails = roomwisebedstatusdetails;
       this.roomtypelist = roomtypelist;
       this.ipregistrationdetails = ipregistrationdetails;
       this.userdetailsByIproomTrackDetailsInUserId = userdetailsByIproomTrackDetailsInUserId;
       this.iproomTrackDetailsPatientRegistrationId = iproomTrackDetailsPatientRegistrationId;
       this.iproomTrackDetailsInDateAndTime = iproomTrackDetailsInDateAndTime;
       this.iproomTrackDetailsOutDateAndTime = iproomTrackDetailsOutDateAndTime;
    }
   
    public Long getIdIproomTrackDetails() {
        return this.idIproomTrackDetails;
    }
    
    public void setIdIproomTrackDetails(Long idIproomTrackDetails) {
        this.idIproomTrackDetails = idIproomTrackDetails;
    }
    public Userdetails getUserdetailsByIproomTrackDetailsOutUserId() {
        return this.userdetailsByIproomTrackDetailsOutUserId;
    }
    
    public void setUserdetailsByIproomTrackDetailsOutUserId(Userdetails userdetailsByIproomTrackDetailsOutUserId) {
        this.userdetailsByIproomTrackDetailsOutUserId = userdetailsByIproomTrackDetailsOutUserId;
    }
    public Roomwisebedstatusdetails getRoomwisebedstatusdetails() {
        return this.roomwisebedstatusdetails;
    }
    
    public void setRoomwisebedstatusdetails(Roomwisebedstatusdetails roomwisebedstatusdetails) {
        this.roomwisebedstatusdetails = roomwisebedstatusdetails;
    }
    public Roomtypelist getRoomtypelist() {
        return this.roomtypelist;
    }
    
    public void setRoomtypelist(Roomtypelist roomtypelist) {
        this.roomtypelist = roomtypelist;
    }
    public Ipregistrationdetails getIpregistrationdetails() {
        return this.ipregistrationdetails;
    }
    
    public void setIpregistrationdetails(Ipregistrationdetails ipregistrationdetails) {
        this.ipregistrationdetails = ipregistrationdetails;
    }
    public Userdetails getUserdetailsByIproomTrackDetailsInUserId() {
        return this.userdetailsByIproomTrackDetailsInUserId;
    }
    
    public void setUserdetailsByIproomTrackDetailsInUserId(Userdetails userdetailsByIproomTrackDetailsInUserId) {
        this.userdetailsByIproomTrackDetailsInUserId = userdetailsByIproomTrackDetailsInUserId;
    }
    public String getIproomTrackDetailsPatientRegistrationId() {
        return this.iproomTrackDetailsPatientRegistrationId;
    }
    
    public void setIproomTrackDetailsPatientRegistrationId(String iproomTrackDetailsPatientRegistrationId) {
        this.iproomTrackDetailsPatientRegistrationId = iproomTrackDetailsPatientRegistrationId;
    }
    public Date getIproomTrackDetailsInDateAndTime() {
        return this.iproomTrackDetailsInDateAndTime;
    }
    
    public void setIproomTrackDetailsInDateAndTime(Date iproomTrackDetailsInDateAndTime) {
        this.iproomTrackDetailsInDateAndTime = iproomTrackDetailsInDateAndTime;
    }
    public Date getIproomTrackDetailsOutDateAndTime() {
        return this.iproomTrackDetailsOutDateAndTime;
    }
    
    public void setIproomTrackDetailsOutDateAndTime(Date iproomTrackDetailsOutDateAndTime) {
        this.iproomTrackDetailsOutDateAndTime = iproomTrackDetailsOutDateAndTime;
    }




}


