package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Opconsultanttransfordetails generated by hbm2java
 */
public class Opconsultanttransfordetails  implements java.io.Serializable {


     private Long idOpconsultantTransforDetails;
     private Outpatientregistration outpatientregistration;
     private Doctordetails doctordetailsByOpconsultantTransforDetailsNewConultantId;
     private Doctordetails doctordetailsByOpconsultantTransforDetailsPrevConsultantId;
     private Userdetails userdetails;
     private Patientregistration patientregistration;
     private Date opconsultantTransforDetailsPrevAppointmentDateAndTime;
     private Date opconsultantTransforDetailsNewAppintmentDateAndTime;

    public Opconsultanttransfordetails() {
    }

    public Opconsultanttransfordetails(Outpatientregistration outpatientregistration, Doctordetails doctordetailsByOpconsultantTransforDetailsNewConultantId, Doctordetails doctordetailsByOpconsultantTransforDetailsPrevConsultantId, Userdetails userdetails, Patientregistration patientregistration, Date opconsultantTransforDetailsPrevAppointmentDateAndTime, Date opconsultantTransforDetailsNewAppintmentDateAndTime) {
       this.outpatientregistration = outpatientregistration;
       this.doctordetailsByOpconsultantTransforDetailsNewConultantId = doctordetailsByOpconsultantTransforDetailsNewConultantId;
       this.doctordetailsByOpconsultantTransforDetailsPrevConsultantId = doctordetailsByOpconsultantTransforDetailsPrevConsultantId;
       this.userdetails = userdetails;
       this.patientregistration = patientregistration;
       this.opconsultantTransforDetailsPrevAppointmentDateAndTime = opconsultantTransforDetailsPrevAppointmentDateAndTime;
       this.opconsultantTransforDetailsNewAppintmentDateAndTime = opconsultantTransforDetailsNewAppintmentDateAndTime;
    }
   
    public Long getIdOpconsultantTransforDetails() {
        return this.idOpconsultantTransforDetails;
    }
    
    public void setIdOpconsultantTransforDetails(Long idOpconsultantTransforDetails) {
        this.idOpconsultantTransforDetails = idOpconsultantTransforDetails;
    }
    public Outpatientregistration getOutpatientregistration() {
        return this.outpatientregistration;
    }
    
    public void setOutpatientregistration(Outpatientregistration outpatientregistration) {
        this.outpatientregistration = outpatientregistration;
    }
    public Doctordetails getDoctordetailsByOpconsultantTransforDetailsNewConultantId() {
        return this.doctordetailsByOpconsultantTransforDetailsNewConultantId;
    }
    
    public void setDoctordetailsByOpconsultantTransforDetailsNewConultantId(Doctordetails doctordetailsByOpconsultantTransforDetailsNewConultantId) {
        this.doctordetailsByOpconsultantTransforDetailsNewConultantId = doctordetailsByOpconsultantTransforDetailsNewConultantId;
    }
    public Doctordetails getDoctordetailsByOpconsultantTransforDetailsPrevConsultantId() {
        return this.doctordetailsByOpconsultantTransforDetailsPrevConsultantId;
    }
    
    public void setDoctordetailsByOpconsultantTransforDetailsPrevConsultantId(Doctordetails doctordetailsByOpconsultantTransforDetailsPrevConsultantId) {
        this.doctordetailsByOpconsultantTransforDetailsPrevConsultantId = doctordetailsByOpconsultantTransforDetailsPrevConsultantId;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Patientregistration getPatientregistration() {
        return this.patientregistration;
    }
    
    public void setPatientregistration(Patientregistration patientregistration) {
        this.patientregistration = patientregistration;
    }
    public Date getOpconsultantTransforDetailsPrevAppointmentDateAndTime() {
        return this.opconsultantTransforDetailsPrevAppointmentDateAndTime;
    }
    
    public void setOpconsultantTransforDetailsPrevAppointmentDateAndTime(Date opconsultantTransforDetailsPrevAppointmentDateAndTime) {
        this.opconsultantTransforDetailsPrevAppointmentDateAndTime = opconsultantTransforDetailsPrevAppointmentDateAndTime;
    }
    public Date getOpconsultantTransforDetailsNewAppintmentDateAndTime() {
        return this.opconsultantTransforDetailsNewAppintmentDateAndTime;
    }
    
    public void setOpconsultantTransforDetailsNewAppintmentDateAndTime(Date opconsultantTransforDetailsNewAppintmentDateAndTime) {
        this.opconsultantTransforDetailsNewAppintmentDateAndTime = opconsultantTransforDetailsNewAppintmentDateAndTime;
    }




}


