package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Oppaymenttrack generated by hbm2java
 */
public class Oppaymenttrack  implements java.io.Serializable {


     private long idOppaymentTrack;
     private Patientregistration patientregistration;
     private Outpatientregistration outpatientregistration;
     private Userdetails userdetails;
     private String oppaymentTrackPaymentType;
     private String oppaymentTrackCreditType;
     private Double oppaymentTrackAmmount;
     private Double oppaymentTrackDiscount;
     private String oppaymentTrackDiscountReason;
     private Double oppaymentTrackPaidAmmount;
     private String oppaymentTrackPaymentStatus;
     private Date oppaymentTrackPaidDateAndTime;

    public Oppaymenttrack() {
    }

	
    public Oppaymenttrack(long idOppaymentTrack) {
        this.idOppaymentTrack = idOppaymentTrack;
    }
    public Oppaymenttrack(long idOppaymentTrack, Patientregistration patientregistration, Outpatientregistration outpatientregistration, Userdetails userdetails, String oppaymentTrackPaymentType, String oppaymentTrackCreditType, Double oppaymentTrackAmmount, Double oppaymentTrackDiscount, String oppaymentTrackDiscountReason, Double oppaymentTrackPaidAmmount, String oppaymentTrackPaymentStatus, Date oppaymentTrackPaidDateAndTime) {
       this.idOppaymentTrack = idOppaymentTrack;
       this.patientregistration = patientregistration;
       this.outpatientregistration = outpatientregistration;
       this.userdetails = userdetails;
       this.oppaymentTrackPaymentType = oppaymentTrackPaymentType;
       this.oppaymentTrackCreditType = oppaymentTrackCreditType;
       this.oppaymentTrackAmmount = oppaymentTrackAmmount;
       this.oppaymentTrackDiscount = oppaymentTrackDiscount;
       this.oppaymentTrackDiscountReason = oppaymentTrackDiscountReason;
       this.oppaymentTrackPaidAmmount = oppaymentTrackPaidAmmount;
       this.oppaymentTrackPaymentStatus = oppaymentTrackPaymentStatus;
       this.oppaymentTrackPaidDateAndTime = oppaymentTrackPaidDateAndTime;
    }
   
    public long getIdOppaymentTrack() {
        return this.idOppaymentTrack;
    }
    
    public void setIdOppaymentTrack(long idOppaymentTrack) {
        this.idOppaymentTrack = idOppaymentTrack;
    }
    public Patientregistration getPatientregistration() {
        return this.patientregistration;
    }
    
    public void setPatientregistration(Patientregistration patientregistration) {
        this.patientregistration = patientregistration;
    }
    public Outpatientregistration getOutpatientregistration() {
        return this.outpatientregistration;
    }
    
    public void setOutpatientregistration(Outpatientregistration outpatientregistration) {
        this.outpatientregistration = outpatientregistration;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public String getOppaymentTrackPaymentType() {
        return this.oppaymentTrackPaymentType;
    }
    
    public void setOppaymentTrackPaymentType(String oppaymentTrackPaymentType) {
        this.oppaymentTrackPaymentType = oppaymentTrackPaymentType;
    }
    public String getOppaymentTrackCreditType() {
        return this.oppaymentTrackCreditType;
    }
    
    public void setOppaymentTrackCreditType(String oppaymentTrackCreditType) {
        this.oppaymentTrackCreditType = oppaymentTrackCreditType;
    }
    public Double getOppaymentTrackAmmount() {
        return this.oppaymentTrackAmmount;
    }
    
    public void setOppaymentTrackAmmount(Double oppaymentTrackAmmount) {
        this.oppaymentTrackAmmount = oppaymentTrackAmmount;
    }
    public Double getOppaymentTrackDiscount() {
        return this.oppaymentTrackDiscount;
    }
    
    public void setOppaymentTrackDiscount(Double oppaymentTrackDiscount) {
        this.oppaymentTrackDiscount = oppaymentTrackDiscount;
    }
    public String getOppaymentTrackDiscountReason() {
        return this.oppaymentTrackDiscountReason;
    }
    
    public void setOppaymentTrackDiscountReason(String oppaymentTrackDiscountReason) {
        this.oppaymentTrackDiscountReason = oppaymentTrackDiscountReason;
    }
    public Double getOppaymentTrackPaidAmmount() {
        return this.oppaymentTrackPaidAmmount;
    }
    
    public void setOppaymentTrackPaidAmmount(Double oppaymentTrackPaidAmmount) {
        this.oppaymentTrackPaidAmmount = oppaymentTrackPaidAmmount;
    }
    public String getOppaymentTrackPaymentStatus() {
        return this.oppaymentTrackPaymentStatus;
    }
    
    public void setOppaymentTrackPaymentStatus(String oppaymentTrackPaymentStatus) {
        this.oppaymentTrackPaymentStatus = oppaymentTrackPaymentStatus;
    }
    public Date getOppaymentTrackPaidDateAndTime() {
        return this.oppaymentTrackPaidDateAndTime;
    }
    
    public void setOppaymentTrackPaidDateAndTime(Date oppaymentTrackPaidDateAndTime) {
        this.oppaymentTrackPaidDateAndTime = oppaymentTrackPaidDateAndTime;
    }




}


