package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Outpatientregistration generated by hbm2java
 */
public class Outpatientregistration  implements java.io.Serializable {


     private String idOutPatientRegistration;
     private Doctordetails doctordetails;
     private Userdetails userdetails;
     private Patientregistration patientregistration;
     private Date outPatientRegistrationAppointmentDateAndTime;
     private Long outPatientRegistrationDaySerialNumber;
     private Integer outPatientRegistrationVisitCount;
     private String outPatientRegistrationStatusOfOp;
     private Date outPatientRegistrationDateAndTime;
     private Set oppaymenttracks = new HashSet(0);
     private Set opconsultanttransfordetailses = new HashSet(0);

    public Outpatientregistration() {
    }

	
    public Outpatientregistration(String idOutPatientRegistration) {
        this.idOutPatientRegistration = idOutPatientRegistration;
    }
    public Outpatientregistration(String idOutPatientRegistration, Doctordetails doctordetails, Userdetails userdetails, Patientregistration patientregistration, Date outPatientRegistrationAppointmentDateAndTime, Long outPatientRegistrationDaySerialNumber, Integer outPatientRegistrationVisitCount, String outPatientRegistrationStatusOfOp, Date outPatientRegistrationDateAndTime, Set oppaymenttracks, Set opconsultanttransfordetailses) {
       this.idOutPatientRegistration = idOutPatientRegistration;
       this.doctordetails = doctordetails;
       this.userdetails = userdetails;
       this.patientregistration = patientregistration;
       this.outPatientRegistrationAppointmentDateAndTime = outPatientRegistrationAppointmentDateAndTime;
       this.outPatientRegistrationDaySerialNumber = outPatientRegistrationDaySerialNumber;
       this.outPatientRegistrationVisitCount = outPatientRegistrationVisitCount;
       this.outPatientRegistrationStatusOfOp = outPatientRegistrationStatusOfOp;
       this.outPatientRegistrationDateAndTime = outPatientRegistrationDateAndTime;
       this.oppaymenttracks = oppaymenttracks;
       this.opconsultanttransfordetailses = opconsultanttransfordetailses;
    }
   
    public String getIdOutPatientRegistration() {
        return this.idOutPatientRegistration;
    }
    
    public void setIdOutPatientRegistration(String idOutPatientRegistration) {
        this.idOutPatientRegistration = idOutPatientRegistration;
    }
    public Doctordetails getDoctordetails() {
        return this.doctordetails;
    }
    
    public void setDoctordetails(Doctordetails doctordetails) {
        this.doctordetails = doctordetails;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Patientregistration getPatientregistration() {
        return this.patientregistration;
    }
    
    public void setPatientregistration(Patientregistration patientregistration) {
        this.patientregistration = patientregistration;
    }
    public Date getOutPatientRegistrationAppointmentDateAndTime() {
        return this.outPatientRegistrationAppointmentDateAndTime;
    }
    
    public void setOutPatientRegistrationAppointmentDateAndTime(Date outPatientRegistrationAppointmentDateAndTime) {
        this.outPatientRegistrationAppointmentDateAndTime = outPatientRegistrationAppointmentDateAndTime;
    }
    public Long getOutPatientRegistrationDaySerialNumber() {
        return this.outPatientRegistrationDaySerialNumber;
    }
    
    public void setOutPatientRegistrationDaySerialNumber(Long outPatientRegistrationDaySerialNumber) {
        this.outPatientRegistrationDaySerialNumber = outPatientRegistrationDaySerialNumber;
    }
    public Integer getOutPatientRegistrationVisitCount() {
        return this.outPatientRegistrationVisitCount;
    }
    
    public void setOutPatientRegistrationVisitCount(Integer outPatientRegistrationVisitCount) {
        this.outPatientRegistrationVisitCount = outPatientRegistrationVisitCount;
    }
    public String getOutPatientRegistrationStatusOfOp() {
        return this.outPatientRegistrationStatusOfOp;
    }
    
    public void setOutPatientRegistrationStatusOfOp(String outPatientRegistrationStatusOfOp) {
        this.outPatientRegistrationStatusOfOp = outPatientRegistrationStatusOfOp;
    }
    public Date getOutPatientRegistrationDateAndTime() {
        return this.outPatientRegistrationDateAndTime;
    }
    
    public void setOutPatientRegistrationDateAndTime(Date outPatientRegistrationDateAndTime) {
        this.outPatientRegistrationDateAndTime = outPatientRegistrationDateAndTime;
    }
    public Set getOppaymenttracks() {
        return this.oppaymenttracks;
    }
    
    public void setOppaymenttracks(Set oppaymenttracks) {
        this.oppaymenttracks = oppaymenttracks;
    }
    public Set getOpconsultanttransfordetailses() {
        return this.opconsultanttransfordetailses;
    }
    
    public void setOpconsultanttransfordetailses(Set opconsultanttransfordetailses) {
        this.opconsultanttransfordetailses = opconsultanttransfordetailses;
    }




}


