package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Roomwisebedstatusdetails generated by hbm2java
 */
public class Roomwisebedstatusdetails  implements java.io.Serializable {


     private long idRoomWiseBedStatusDetails;
     private Roomtypelist roomtypelist;
     private String roomWiseBedStatusDetailsBedNumber;
     private String roomWiseBedStatusDetailsBedStatus;
     private Set iproomtrackdetailses = new HashSet(0);

    public Roomwisebedstatusdetails() {
    }

	
    public Roomwisebedstatusdetails(long idRoomWiseBedStatusDetails) {
        this.idRoomWiseBedStatusDetails = idRoomWiseBedStatusDetails;
    }
    public Roomwisebedstatusdetails(long idRoomWiseBedStatusDetails, Roomtypelist roomtypelist, String roomWiseBedStatusDetailsBedNumber, String roomWiseBedStatusDetailsBedStatus, Set iproomtrackdetailses) {
       this.idRoomWiseBedStatusDetails = idRoomWiseBedStatusDetails;
       this.roomtypelist = roomtypelist;
       this.roomWiseBedStatusDetailsBedNumber = roomWiseBedStatusDetailsBedNumber;
       this.roomWiseBedStatusDetailsBedStatus = roomWiseBedStatusDetailsBedStatus;
       this.iproomtrackdetailses = iproomtrackdetailses;
    }
   
    public long getIdRoomWiseBedStatusDetails() {
        return this.idRoomWiseBedStatusDetails;
    }
    
    public void setIdRoomWiseBedStatusDetails(long idRoomWiseBedStatusDetails) {
        this.idRoomWiseBedStatusDetails = idRoomWiseBedStatusDetails;
    }
    public Roomtypelist getRoomtypelist() {
        return this.roomtypelist;
    }
    
    public void setRoomtypelist(Roomtypelist roomtypelist) {
        this.roomtypelist = roomtypelist;
    }
    public String getRoomWiseBedStatusDetailsBedNumber() {
        return this.roomWiseBedStatusDetailsBedNumber;
    }
    
    public void setRoomWiseBedStatusDetailsBedNumber(String roomWiseBedStatusDetailsBedNumber) {
        this.roomWiseBedStatusDetailsBedNumber = roomWiseBedStatusDetailsBedNumber;
    }
    public String getRoomWiseBedStatusDetailsBedStatus() {
        return this.roomWiseBedStatusDetailsBedStatus;
    }
    
    public void setRoomWiseBedStatusDetailsBedStatus(String roomWiseBedStatusDetailsBedStatus) {
        this.roomWiseBedStatusDetailsBedStatus = roomWiseBedStatusDetailsBedStatus;
    }
    public Set getIproomtrackdetailses() {
        return this.iproomtrackdetailses;
    }
    
    public void setIproomtrackdetailses(Set iproomtrackdetailses) {
        this.iproomtrackdetailses = iproomtrackdetailses;
    }




}


