package com.shms.dbmodel;
// Generated Oct 30, 2013 8:55:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userdetails generated by hbm2java
 */
public class Userdetails  implements java.io.Serializable {


     private String idUserDetails;
     private String userDetailsFirstName;
     private String userDetailsLastName;
     private Integer userDetailsAge;
     private String userDetailsSex;
     private Long userDetailsContactNumber;
     private Date userDetailsDateOfJoining;
     private String userDetailsDesignation;
     private String userDetailsPassword;
     private String userDetailsAddress;
     private Set ipconstranfordetailses = new HashSet(0);
     private Set oppaymenttracks = new HashSet(0);
     private Set iproomtrackdetailsesForIproomTrackDetailsOutUserId = new HashSet(0);
     private Set iproomtrackdetailsesForIproomTrackDetailsInUserId = new HashSet(0);
     private Set outpatientregistrations = new HashSet(0);
     private Set ipregistrationdetailses = new HashSet(0);
     private Set opconsultanttransfordetailses = new HashSet(0);
     private Set patientregistrations = new HashSet(0);

    public Userdetails() {
    }

	
    public Userdetails(String idUserDetails) {
        this.idUserDetails = idUserDetails;
    }
    public Userdetails(String idUserDetails, String userDetailsFirstName, String userDetailsLastName, Integer userDetailsAge, String userDetailsSex, Long userDetailsContactNumber, Date userDetailsDateOfJoining, String userDetailsDesignation, String userDetailsPassword, String userDetailsAddress, Set ipconstranfordetailses, Set oppaymenttracks, Set iproomtrackdetailsesForIproomTrackDetailsOutUserId, Set iproomtrackdetailsesForIproomTrackDetailsInUserId, Set outpatientregistrations, Set ipregistrationdetailses, Set opconsultanttransfordetailses, Set patientregistrations) {
       this.idUserDetails = idUserDetails;
       this.userDetailsFirstName = userDetailsFirstName;
       this.userDetailsLastName = userDetailsLastName;
       this.userDetailsAge = userDetailsAge;
       this.userDetailsSex = userDetailsSex;
       this.userDetailsContactNumber = userDetailsContactNumber;
       this.userDetailsDateOfJoining = userDetailsDateOfJoining;
       this.userDetailsDesignation = userDetailsDesignation;
       this.userDetailsPassword = userDetailsPassword;
       this.userDetailsAddress = userDetailsAddress;
       this.ipconstranfordetailses = ipconstranfordetailses;
       this.oppaymenttracks = oppaymenttracks;
       this.iproomtrackdetailsesForIproomTrackDetailsOutUserId = iproomtrackdetailsesForIproomTrackDetailsOutUserId;
       this.iproomtrackdetailsesForIproomTrackDetailsInUserId = iproomtrackdetailsesForIproomTrackDetailsInUserId;
       this.outpatientregistrations = outpatientregistrations;
       this.ipregistrationdetailses = ipregistrationdetailses;
       this.opconsultanttransfordetailses = opconsultanttransfordetailses;
       this.patientregistrations = patientregistrations;
    }
   
    public String getIdUserDetails() {
        return this.idUserDetails;
    }
    
    public void setIdUserDetails(String idUserDetails) {
        this.idUserDetails = idUserDetails;
    }
    public String getUserDetailsFirstName() {
        return this.userDetailsFirstName;
    }
    
    public void setUserDetailsFirstName(String userDetailsFirstName) {
        this.userDetailsFirstName = userDetailsFirstName;
    }
    public String getUserDetailsLastName() {
        return this.userDetailsLastName;
    }
    
    public void setUserDetailsLastName(String userDetailsLastName) {
        this.userDetailsLastName = userDetailsLastName;
    }
    public Integer getUserDetailsAge() {
        return this.userDetailsAge;
    }
    
    public void setUserDetailsAge(Integer userDetailsAge) {
        this.userDetailsAge = userDetailsAge;
    }
    public String getUserDetailsSex() {
        return this.userDetailsSex;
    }
    
    public void setUserDetailsSex(String userDetailsSex) {
        this.userDetailsSex = userDetailsSex;
    }
    public Long getUserDetailsContactNumber() {
        return this.userDetailsContactNumber;
    }
    
    public void setUserDetailsContactNumber(Long userDetailsContactNumber) {
        this.userDetailsContactNumber = userDetailsContactNumber;
    }
    public Date getUserDetailsDateOfJoining() {
        return this.userDetailsDateOfJoining;
    }
    
    public void setUserDetailsDateOfJoining(Date userDetailsDateOfJoining) {
        this.userDetailsDateOfJoining = userDetailsDateOfJoining;
    }
    public String getUserDetailsDesignation() {
        return this.userDetailsDesignation;
    }
    
    public void setUserDetailsDesignation(String userDetailsDesignation) {
        this.userDetailsDesignation = userDetailsDesignation;
    }
    public String getUserDetailsPassword() {
        return this.userDetailsPassword;
    }
    
    public void setUserDetailsPassword(String userDetailsPassword) {
        this.userDetailsPassword = userDetailsPassword;
    }
    public String getUserDetailsAddress() {
        return this.userDetailsAddress;
    }
    
    public void setUserDetailsAddress(String userDetailsAddress) {
        this.userDetailsAddress = userDetailsAddress;
    }
    public Set getIpconstranfordetailses() {
        return this.ipconstranfordetailses;
    }
    
    public void setIpconstranfordetailses(Set ipconstranfordetailses) {
        this.ipconstranfordetailses = ipconstranfordetailses;
    }
    public Set getOppaymenttracks() {
        return this.oppaymenttracks;
    }
    
    public void setOppaymenttracks(Set oppaymenttracks) {
        this.oppaymenttracks = oppaymenttracks;
    }
    public Set getIproomtrackdetailsesForIproomTrackDetailsOutUserId() {
        return this.iproomtrackdetailsesForIproomTrackDetailsOutUserId;
    }
    
    public void setIproomtrackdetailsesForIproomTrackDetailsOutUserId(Set iproomtrackdetailsesForIproomTrackDetailsOutUserId) {
        this.iproomtrackdetailsesForIproomTrackDetailsOutUserId = iproomtrackdetailsesForIproomTrackDetailsOutUserId;
    }
    public Set getIproomtrackdetailsesForIproomTrackDetailsInUserId() {
        return this.iproomtrackdetailsesForIproomTrackDetailsInUserId;
    }
    
    public void setIproomtrackdetailsesForIproomTrackDetailsInUserId(Set iproomtrackdetailsesForIproomTrackDetailsInUserId) {
        this.iproomtrackdetailsesForIproomTrackDetailsInUserId = iproomtrackdetailsesForIproomTrackDetailsInUserId;
    }
    public Set getOutpatientregistrations() {
        return this.outpatientregistrations;
    }
    
    public void setOutpatientregistrations(Set outpatientregistrations) {
        this.outpatientregistrations = outpatientregistrations;
    }
    public Set getIpregistrationdetailses() {
        return this.ipregistrationdetailses;
    }
    
    public void setIpregistrationdetailses(Set ipregistrationdetailses) {
        this.ipregistrationdetailses = ipregistrationdetailses;
    }
    public Set getOpconsultanttransfordetailses() {
        return this.opconsultanttransfordetailses;
    }
    
    public void setOpconsultanttransfordetailses(Set opconsultanttransfordetailses) {
        this.opconsultanttransfordetailses = opconsultanttransfordetailses;
    }
    public Set getPatientregistrations() {
        return this.patientregistrations;
    }
    
    public void setPatientregistrations(Set patientregistrations) {
        this.patientregistrations = patientregistrations;
    }




}


